package com.offline_First.ui.theme

import androidx.compose.ui.graphics.Color

val EduNovaPrimary = Color(0xFF2A8F93)
val EduNovaPrimaryContainer = Color(0xFFDDF2EE)
val EduNovaSecondary = Color(0xFF24777B)
val EduNovaSecondaryContainer = Color(0xFFA8DCD5)
val EduNovaAccent = Color(0xFFA8DCD5)
val EduNovaSuccess = Color(0xFF74A98A)
val EduNovaBackground = Color(0xFFFFF8EE)
val EduNovaSurface = Color(0xFFFFFBF5)
val EduNovaSurfaceVariant = Color(0xFFDDF2EE)
val EduNovaTextPrimary = Color(0xFF2B2133)
val EduNovaTextSecondary = Color(0xFF6B6570)
val EduNovaBorder = Color(0xFFE7DDD2)
val EduNovaError = Color(0xFFC96A6A)
val EduNovaWarning = Color(0xFFC99A58)

val EduNovaPrimaryDark = Color(0xFF7BC4C5)
val EduNovaPrimaryContainerDark = Color(0xFF155D61)
val EduNovaSecondaryDark = Color(0xFF8FCBC7)
val EduNovaSecondaryContainerDark = Color(0xFF1E5659)
val EduNovaAccentDark = Color(0xFF8FCFC6)
val EduNovaBackgroundDark = Color(0xFF211A1F)
val EduNovaSurfaceDark = Color(0xFF211A1F)
val EduNovaSurfaceVariantDark = Color(0xFF4D4442)
val EduNovaTextPrimaryDark = Color(0xFFF4EAE1)
val EduNovaTextSecondaryDark = Color(0xFFD8CBC4)
val EduNovaBorderDark = Color(0xFFA99B8F)
val EduNovaErrorDark = Color(0xFFF3A7A0)
val EduNovaWarningDark = Color(0xFFF0C078)