package com.offline_First.ui.theme

import androidx.compose.ui.graphics.Color

val EduNovaPrimary = Color(0xFF665276)
val EduNovaPrimaryContainer = Color(0xFFEDE5F2)
val EduNovaSecondary = Color(0xFF7A6A8A)
val EduNovaSecondaryContainer = Color(0xFFF1ECF5)
val EduNovaAccent = Color(0xFF5D8A76)
val EduNovaSuccess = Color(0xFF4D8068)
val EduNovaBackground = Color(0xFFFAF8F5)
val EduNovaSurface = Color(0xFFFFFCF8)
val EduNovaSurfaceVariant = Color(0xFFF1EDF2)
val EduNovaTextPrimary = Color(0xFF2D2933)
val EduNovaTextSecondary = Color(0xFF6D6575)
val EduNovaBorder = Color(0xFFE3D8E8)
val EduNovaError = Color(0xFFBA1A1A)
val EduNovaWarning = Color(0xFF8A6A2F)

val EduNovaPrimaryDark = Color(0xFFD8BFE5)
val EduNovaPrimaryContainerDark = Color(0xFF513D61)
val EduNovaSecondaryDark = Color(0xFFD2C1D9)
val EduNovaSecondaryContainerDark = Color(0xFF5A4966)
val EduNovaAccentDark = Color(0xFFA8D5BC)
val EduNovaBackgroundDark = Color(0xFF201D21)
val EduNovaSurfaceDark = Color(0xFF201D21)
val EduNovaSurfaceVariantDark = Color(0xFF49434B)
val EduNovaTextPrimaryDark = Color(0xFFEAE1E8)
val EduNovaTextSecondaryDark = Color(0xFFD0C5CF)
val EduNovaBorderDark = Color(0xFF958C96)
val EduNovaErrorDark = Color(0xFFFFB4AB)
val EduNovaWarningDark = Color(0xFFE7C37A)