"""Phase1_Core_Schema: Add course categories, courses, modules, lessons, roadmaps

Revision ID: fd5a2e32997d
Revises: 0c9897f27723
Create Date: 2026-10-04 20:31:59.957936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd5a2e32997d'
down_revision: Union[str, None] = '0c9897f27723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_course_categories_display_order', 'course_categories', ['display_order'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('accent_theme', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IN ('Beginner', 'Intermediate', 'Advanced', 'All Levels')", name='ck_roadmaps_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_roadmaps_system_category', 'roadmaps', ['is_system', 'category'], unique=False)
    op.create_index('ix_roadmaps_user_id', 'roadmaps', ['user_id'], unique=False, postgresql_where='user_id IS NOT NULL')
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('education_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("education_mode IN ('school', 'general')", name='ck_user_profiles_education_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('accent_color', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IN ('Beginner', 'Intermediate', 'Advanced')", name='ck_courses_level'),
    sa.CheckConstraint("status IN ('active', 'archived', 'draft')", name='ck_courses_status'),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_courses_category_id', 'courses', ['category_id'], unique=False)
    op.create_index('ix_courses_status_featured', 'courses', ['status', 'is_featured'], unique=False)
    op.create_table('course_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_course_modules_display_order'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_modules_course_display', 'course_modules', ['course_id', 'display_order'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_roadmap_items_display_order'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roadmap_items_course_id', 'roadmap_items', ['course_id'], unique=False, postgresql_where='course_id IS NOT NULL')
    op.create_index('ix_roadmap_items_roadmap_display', 'roadmap_items', ['roadmap_id', 'display_order'], unique=False)
    op.create_table('user_course_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed')", name='ck_user_course_progress_status'),
    sa.CheckConstraint('completion_percentage >= 0.0 AND completion_percentage <= 100.0', name='ck_user_course_progress_percentage'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_course_progress_user_course', 'user_course_progress', ['user_id', 'course_id'], unique=True)
    op.create_index('ix_user_course_progress_user_status', 'user_course_progress', ['user_id', 'status'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("content_type IN ('video', 'article', 'quiz', 'exercise', 'project')", name='ck_lessons_content_type'),
    sa.CheckConstraint('display_order >= 0', name='ck_lessons_display_order'),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lessons_module_display', 'lessons', ['module_id', 'display_order'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_lesson_progress_user_completed', 'user_lesson_progress', ['user_id', 'completed'], unique=False)
    op.create_index('ix_user_lesson_progress_user_lesson', 'user_lesson_progress', ['user_id', 'lesson_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_lesson_progress_user_lesson', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_user_completed', table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index('ix_lessons_module_display', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_user_course_progress_user_status', table_name='user_course_progress')
    op.drop_index('ix_user_course_progress_user_course', table_name='user_course_progress')
    op.drop_table('user_course_progress')
    op.drop_index('ix_roadmap_items_roadmap_display', table_name='roadmap_items')
    op.drop_index('ix_roadmap_items_course_id', table_name='roadmap_items', postgresql_where='course_id IS NOT NULL')
    op.drop_table('roadmap_items')
    op.drop_index('ix_course_modules_course_display', table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('ix_courses_status_featured', table_name='courses')
    op.drop_index('ix_courses_category_id', table_name='courses')
    op.drop_table('courses')
    op.drop_table('user_profiles')
    op.drop_index('ix_roadmaps_user_id', table_name='roadmaps', postgresql_where='user_id IS NOT NULL')
    op.drop_index('ix_roadmaps_system_category', table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index('ix_course_categories_display_order', table_name='course_categories')
    op.drop_table('course_categories')
    # ### end Alembic commands ###
